---
title: "demo visualization"
author: "Juhyun"
date: "`r Sys.Date()`"
output: pdf_document
---

### Libraries
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(modelr)
library(boot)
```

### Import Dataset
```{r}
data <- read.csv("climate_change_impact_on_agriculture_2024.csv")
```

### Preparation and cleaning the data

```{r}
# mutate continent columns

country_to_continent <- data.frame(
  Country = c("Argentina", "Australia", "Brazil","Canada","China","France",
              "India","Nigeria", "Russia","USA"),
  Continent = c("South America", "Oceania", "South America", 
                "North America", "East Asia", "Europe", 
                "South Asia", "Africa","Eurasia","North America")
)

data_with_continent <- data %>%
  left_join(country_to_continent, by = "Country") 

data <- data_with_continent %>%
  select(Year, Country, Continent, Region, everything())

```

```{r}
aggregated_data <- data %>%
  group_by(Year, Continent) %>%
  summarize(
    avg_crop_yield = mean(Crop_Yield_MT_per_HA, na.rm = TRUE),
    avg_extreme_weather_events =mean(Extreme_Weather_Events, na.rm= TRUE),
    avg_temp_c = mean(Average_Temperature_C, na.rm = TRUE),
    avg_total_precipitation_mm = mean(Total_Precipitation_mm, na.rm = TRUE),
    avg_co2_emissions_mt = mean(CO2_Emissions_MT, na.rm =TRUE),
    avg_pesticide_use_kg_per_ha = mean(Pesticide_Use_KG_per_HA, na.rm=TRUE),
    avg_fertilizer_use_kg_per_ha = mean(Fertilizer_Use_KG_per_HA, na.rm =TRUE),
    avg_soil_health_index = mean(Soil_Health_Index, na.rm=TRUE),
    avg_economic_impact_million_usd = mean(Economic_Impact_Million_USD, na.rm = TRUE)
  ) %>%
  ungroup() 

```

```{r}
data <- data %>%
  left_join(aggregated_data, by = c("Year", "Continent"))

data_constracted <- data %>%
  select(-c(6:9, 12:14, 16))
```
#### avg_temp vs avg_crop_yield

Crop_Type
```{r}
train_df %>%
  group_by(Crop_Type) %>%
  summarize(count = n())
ggplot(train_df, aes(x = avg_temp_c, y = avg_crop_yield)) +
  geom_point(aes(color = Crop_Type), alpha = 0.7) + # Scatterplot with transparency
  geom_smooth(method = "lm", se = TRUE, color = "black") + # Add regression lines
  labs(
    title = "Relationship Between Average Temperature and Crop Yield by Continent",
    x = "Average Temperature (°C)",
    y = "Crop Yield (MT/HA)"
  ) +
  facet_wrap(~Continent, scales = "free") + # Separate graphs by continent
  theme_minimal() +
  theme(
    strip.text = element_text(size = 12, face = "bold") # Style facet labels
  )
```
#### precipitation vs crop yield
```{r}
train_df %>%
  group_by(Crop_Type) %>%
  summarize(count = n())
ggplot(train_df, aes(x = avg_total_precipitation_mm, y = avg_crop_yield)) +
  geom_point(aes(color = Crop_Type), alpha = 0.7) + # Scatterplot with transparency
  geom_smooth(method = "lm", se = TRUE, color = "black") + # Add regression lines
  labs(
    title = "Relationship Between Average Temperature and Crop Yield by Continent",
    x = "Average Temperature (°C)",
    y = "Crop Yield (MT/HA)"
  ) +
  facet_wrap(~Continent, scales = "free") + # Separate graphs by continent
  theme_minimal() +
  theme(
    strip.text = element_text(size = 12, face = "bold") # Style facet labels
  )
```
```{r}
train_df %>%
  group_by(Crop_Type) %>%
  summarize(count = n())
ggplot(train_df, aes(x = avg_co2_emissions_mt, y = avg_crop_yield)) +
  geom_point(aes(color = Crop_Type), alpha = 0.7) + # Scatterplot with transparency
  geom_smooth(method = "lm", se = TRUE, color = "black") + # Add regression lines
  labs(
    title = "Relationship Between Average Temperature and Crop Yield by Continent",
    x = "Average Temperature (°C)",
    y = "Crop Yield (MT/HA)"
  ) +
  facet_wrap(~Continent, scales = "free") + # Separate graphs by continent
  theme_minimal() +
  theme(
    strip.text = element_text(size = 12, face = "bold") # Style facet labels
  )
```
```{r}
train_df %>%
  group_by(Crop_Type) %>%
  summarize(count = n())
ggplot(train_df, aes(x = avg_fertilizer_use_kg_per_ha, y = avg_soil_health_index)) +
  geom_point(aes(color = Crop_Type), alpha = 0.7) + # Scatterplot with transparency
  geom_smooth(method = "lm", se = TRUE, color = "black") + # Add regression lines
  labs(
    title = "Relationship Between Average Temperature and Crop Yield by Continent",
    x = "Average Temperature (°C)",
    y = "Crop Yield (MT/HA)"
  ) +
  facet_wrap(~Continent, scales = "free") + # Separate graphs by continent
  theme_minimal() +
  theme(
    strip.text = element_text(size = 12, face = "bold") # Style facet labels
  )
```
```{r}
train_df %>%
  group_by(Crop_Type) %>%
  summarize(count = n())
ggplot(train_df, aes(x = avg_pesticide_use_kg_per_ha, y = avg_soil_health_index)) +
  geom_point(aes(color = Crop_Type), alpha = 0.7) + # Scatterplot with transparency
  geom_smooth(method = "lm", se = TRUE, color = "black") + # Add regression lines
  labs(
    title = "Relationship Between Average Temperature and Crop Yield by Continent",
    x = "Average Temperature (°C)",
    y = "Crop Yield (MT/HA)"
  ) +
  facet_wrap(~Continent, scales = "free") + # Separate graphs by continent
  theme_minimal() +
  theme(
    strip.text = element_text(size = 12, face = "bold") # Style facet labels
  )
```
